/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description APIの稼働状態を確認する。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health check API */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 建物一覧取得
         * @description キャンパス内でARマーカーが設置されている建物（エリア）の一覧を取得する。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get list of buildings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                marker_count: number;
                            }[];
                        };
                    };
                };
                /** @description 建物一覧の取得に失敗しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{building_id}/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 建物内スポット一覧取得
         * @description 指定した建物IDに紐づくスポット（ARマーカー）の一覧を名前順で取得する。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    building_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get list of spots in the building */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                description: string | null;
                                marker_id: string;
                            }[];
                        };
                    };
                };
                /** @description リクエストの内容が不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 指定された建物が見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description スポット一覧の取得に失敗しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots/{marker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スポット詳細情報取得
         * @description スキャンしたARマーカーIDに紐づく詳細情報とARアセットを取得する。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    marker_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get spots by marker ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                description: string | null;
                                building: {
                                    id: string;
                                    name: string;
                                };
                                ar_assets: {
                                    type: string;
                                    url: string;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description リクエストの内容が不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description スポット情報の取得に失敗しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * センサ計測値の登録
         * @description 学内に設置したIoTデバイスから送信されるセンサ計測値を保存する。デバイス認証は Authorization: Bearer <SENSOR_INGEST_KEY> で行う。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sensor_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        value: number;
                        /** Format: date-time */
                        recorded_at?: string;
                    };
                };
            };
            responses: {
                /** @description Reading recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                sensor_id: string;
                                value: number;
                                recorded_at: string;
                                created_at: string;
                            };
                        };
                    };
                };
                /** @description リクエストの内容が不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 指定されたセンサが見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description センサ計測値の保存に失敗しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 訪問履歴取得
         * @description ユーザーの訪問履歴を一覧で取得する。Authorization: Bearer <JWT> による認証が必要。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get user visits */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                spot_id: string;
                                visited_at: string;
                            }[];
                        };
                    };
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 訪問記録の作成
         * @description ユーザーが特定のスポットを訪問（ARコンテンツを閲覧）したことを記録する。Authorization: Bearer <JWT> による認証が必要。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        spot_id: string;
                    };
                };
            };
            responses: {
                /** @description Visit recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                spot_id: string;
                                visited_at: string;
                            };
                        };
                    };
                };
                /** @description リクエストの内容が不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 認証に失敗しました */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント一覧取得
         * @description キャンパス内で開催されるイベント情報の一覧を開始時刻の昇順で取得する。upcoming=true を指定すると、終了していない（現在時刻以降に終了する）イベントのみを返す。
         */
        get: {
            parameters: {
                query?: {
                    /** @description true の場合、終了していないイベントのみを返す。 */
                    upcoming?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get list of events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                title: string;
                                description: string | null;
                                start_time: string;
                                end_time: string;
                            }[];
                        };
                    };
                };
                /** @description リクエストの内容が不正です */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description イベント一覧の取得に失敗しました */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description エラー種別を示す機械可読なコード
                 * @example not_found
                 */
                code: string;
                /**
                 * @description 人間向けのエラーメッセージ（日本語）
                 * @example 指定されたリソースが見つかりません
                 */
                message: string;
                /** @description バリデーションエラーの詳細など、補足情報（任意） */
                details?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
